services:
  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db

pipeline:
  test:
    image: python:3.6-alpine3.7
    commands:
      - pip install -r requirements/ci.txt --no-cache-dir
      - bash scripts/wait-for-it.sh $${DATABASE_HOST} $${DATABASE_PORT}
      - bash scripts/run-tests.sh --ci
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    when:
      event: [pull_request, push, tag]

  build-docker-image-tag:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec-walhall/django_service_blueprint
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]

  prebuild-docker-static-image:
    image: python:3.6-alpine3.7
    commands:
      - bash scripts/run-collectstatic.sh
    when:
      event: [tag]
      status: [success]

  build-docker-static-image-tag:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec-walhall/django_rest_boilerplate_static
    dockerfile: Dockerfile.nginx
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]
