services:
  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db

pipeline:
  test:
    image: python:3.6-alpine3.7
    commands:
      - apk add --no-cache postgresql-libs bash
      - apk add --no-cache --virtual .build-deps git python-dev gcc musl-dev postgresql-dev libffi-dev libressl-dev
      - pip install --upgrade pip
      - pip install -r requirements/ci.txt --no-cache-dir
      - bash scripts/wait-for-it.sh $${DATABASE_HOST} $${DATABASE_PORT}
      - pytest -v
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    when:
      event: [pull_request, push, tag]

  build-docker-image-tag:
    image: plugins/docker
    registry:
      from_secret: DOCKER_REGISTRY
    repo:
      from_secret: DOCKER_REPO
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    auto_tag: true
    insecure: true
    file: Dockerfile
    when:
      event: [push, tag]
      status: [success]
