services:
  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db

pipeline:
  test:
    image: python:3.6-alpine3.7
    commands:
      - apk add --no-cache postgresql-libs bash
      - apk add --no-cache --virtual .build-deps git python-dev gcc musl-dev postgresql-dev libffi-dev libressl-dev
      - pip install --upgrade pip
      - pip install -r requirements/ci.txt --no-cache-dir
      - bash scripts/wait-for-it.sh $${DATABASE_HOST} $${DATABASE_PORT}
      - bash scripts/run-tests.sh --ci
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    when:
      event: [pull_request, push, tag]

  build-docker-image:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec-walhall/app_name
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]
